services:
    ongr_filter_manager.twig.pager_extension:
            class: ONGR\FilterManagerBundle\Twig\PagerExtension
            arguments:
                - '@router'
            tags:
                - { name: twig.extension }
