parameters:
    ongr_filter_manager.twig.pager_extension.class: ONGR\FilterManagerBundle\Twig\PagerExtension

services:
    ongr_filter_manager.twig.pager_extension:
            class: %ongr_filter_manager.twig.pager_extension.class%
            arguments:
                - @router
            tags:
                - { name: twig.extension }
