parameters:
    ongr_filter_manager.twig.pager_extension.class: ONGR\FilterManagerBundle\Twig\PagerExtension
    ongr_filter_manager.filter_map:
        choice: ONGR\FilterManagerBundle\Filters\Widget\Choice\SingleTermChoice
        multi_choice: ONGR\FilterManagerBundle\Filters\Widget\Choice\MultiTermChoice
        match: ONGR\FilterManagerBundle\Filters\Widget\Search\MatchSearch
        document_field: ONGR\FilterManagerBundle\Filters\Widget\Search\DocumentField
        sort: ONGR\FilterManagerBundle\Filters\Widget\Sort\Sort
        pager: ONGR\FilterManagerBundle\Filters\Widget\Pager\Pager
        range: ONGR\FilterManagerBundle\Filters\Widget\Range\Range

services:
    ongr_filter_manager.twig.pager_extension:
            class: %ongr_filter_manager.twig.pager_extension.class%
            arguments:
                - @router
            tags:
                - { name: twig.extension }
